name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Run backend build
      run: |
        cd backend
        npm run build --if-present

    - name: Run backend tests
      run: |
        cd backend
        npm test
